config/urls.py
from functools import partial

from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import include
from django.urls import path
from django.urls import reverse
from django.views import defaults as default_views

from leerming.profiles.decorators import profile_required

decorator_include_login_and_profile = partial(
    decorator_include,
    (login_required, profile_required),
)

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("schema-viewer/", include("schema_viewer.urls")),
    path("account/", include("allauth.urls")),
    path(
        "profiles/",
        decorator_include(
            login_required, "leerming.profiles.urls", namespace="profiles"
        ),
    ),
    path(
        "flashcards/",
        decorator_include_login_and_profile(
            "leerming.flashcards.urls", namespace="flashcards"
        ),
    ),
    path(
        "reviews/",
        decorator_include_login_and_profile(
            "leerming.reviews.urls", namespace="reviews"
        ),
    ),
    path(
        "gifts/",
        decorator_include_login_and_profile("leerming.gifts.urls", namespace="gifts"),
    ),
    path(
        "documents/",
        decorator_include_login_and_profile(
            "leerming.documents.urls", namespace="documents"
        ),
    ),
    path(
        "",
        lambda request: HttpResponseRedirect(reverse("flashcards:index")),
        name="home",
    ),  # TODO: replace by a landing page at some point
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

leerming/flashcards/urls.py
from django.urls import path

from . import views

app_name = "flashcards"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path(
        "create-from-document/", views.create_from_document, name="create_from_document"
    ),
    path("triage/", views.triage, name="triage"),
    path(
        "edit-llm-flashcard/<str:id>/",
        views.edit_llm_flashcard,
        name="edit_llm_flashcard",
    ),
    path("save-llm-flashcards/", views.save_llm_flashcards, name="save_llm_flashcards"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/show-answer/", views.show_answer, name="show_answer"),
    path("<int:pk>/show-question/", views.show_question, name="show_question"),
]

leerming/gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"

urlpatterns = [
    path("", views.index, name="index"),
    path("set-recipient/", views.set_recipient, name="set_recipient"),
    path("confirm-send/", views.confirm_send, name="confirm_send"),
    path("cancel-send/", views.cancel_send, name="cancel_send"),
    path("open/<int:pk>/", views.open_gift, name="open"),
]

leerming/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
]

leerming/reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"


urlpatterns = [
    path("", views.index, name="index"),
    path("no-cards-to-review/", views.no_cards_to_review, name="no_cards_to_review"),
    path("start/", views.start, name="start"),
    path("show-current-card/", views.show_current_card, name="show_current_card"),
    path("move-to-next-card/", views.move_to_next_card, name="move_to_next_card"),
    path("end/", views.end, name="end"),
    path("reveal-answer/", views.reveal_answer, name="reveal_answer"),
    path("answer-card/", views.answer_card, name="answer_card"),
    path("<review_id>/", views.details, name="details"),
]

leerming/core/views.py
from django.shortcuts import render
from django.http import HttpRequest


def index(request: HttpRequest):
    return render(request, "core/index.html")

leerming/documents/views.py
from django.db import IntegrityError
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django_htmx.http import reswap
from django_htmx.http import retarget
from django_htmx.http import trigger_client_event
from django_q.tasks import async_task
from django_q.tasks import result

from .forms import UploadForm
from .models import UploadedDocument
from leerming.users.models import User


def _create_document(doc_type: str, owner_id: int, params: dict) -> int | None:
    owner = User.objects.get(id=owner_id)
    create_func = UploadedDocument.get_create_func(doc_type)
    try:
        doc = create_func(owner=owner, **params)
        return doc.id
    except IntegrityError:
        return


def select(request: HttpRequest):
    documents = request.user.uploaded_documents.all().order_by("-created")
    response = TemplateResponse(
        request,
        "documents/select.html",
        {
            "documents": documents,
            "selected": int(request.GET.get("selected", default=documents.first().id)),
        },
    )
    if new_target := request.GET.get("retarget"):
        response = retarget(response, f"#{new_target}")
    return trigger_client_event(response, "showSubmitBtn", {})


def upload(request: HttpRequest):
    data = (request.POST, request.FILES) if request.method == "POST" else (None, None)
    form = UploadForm(*data, context={"user": request.user})
    if form.is_valid():
        cleaned_data = form.cleaned_data
        task_id = async_task(
            _create_document,
            doc_type=cleaned_data.pop("doc_type"),
            owner_id=request.user.id,
            params=cleaned_data,
        )
        return redirect(reverse("documents:upload_progress", args=[task_id]))
    response = TemplateResponse(
        request,
        "documents/upload.html",
        {
            "form": form,
            "user_has_existing_documents": request.user.uploaded_documents.exists(),
        },
    )
    if not form.is_valid() and request.method == "POST":
        response = retarget(response, "#upload-card")
        return reswap(response, "outerHTML")
    return trigger_client_event(response, "hideSubmitBtn", {})


def upload_progress(request: HttpRequest, task_id: str):
    return TemplateResponse(
        request, "documents/upload_progress.html", {"task_id": task_id}
    )


#  try for 6 min max for now, query for the result every 3 seconds with a max of 120 attempts
MAX_NBR_OF_TRY = 120
MILLISECONDS_WAIT = 3000


def upload_status(request: HttpRequest, task_id: str):
    nbr_of_try = request.session.get("nbr_of_try", 1)
    select_url = reverse("documents:select") + "?retarget=upload-card"
    if nbr_of_try > MAX_NBR_OF_TRY:
        # maybe add a message to tell the user to retry or check if task failed
        del request.session["nbr_of_try"]
        return redirect(select_url)
    request.session["nbr_of_try"] = nbr_of_try + 1
    if document_id := result(task_id, MILLISECONDS_WAIT):
        del request.session["nbr_of_try"]
        return redirect(f"{select_url}&selected={document_id}")
    return redirect(reverse("documents:upload_progress", args=[task_id]))


def get_form(request: HttpRequest):
    return HttpResponse(UploadForm(initial=request.GET).render())


def index(request: HttpRequest):
    if request.user.uploaded_documents.exists():
        return redirect("documents:select")
    return redirect("documents:upload")

leerming/flashcards/views.py
from django.core.paginator import Paginator
from django.db import models
from django.http import Http404
from django.http import HttpRequest
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseClientRedirect

from ..documents.models import UploadedDocument
from .filters import FilterForm
from .forms import FlashCardCreateForm
from .forms import FlashCardEditForm
from .forms import FlashCardFromDocument
from .forms import LLMFlashCard
from .llm_utils import delete_llm_flashcards_from_session
from .llm_utils import load_llm_flashcards_from_session
from .llm_utils import make_flashcards_from
from .llm_utils import save_llm_flashcards_to_session
from .models import FlashCard
from .models import Topic


def index(request: HttpRequest):
    form = FilterForm(request.GET or None, request=request)
    flashcards = form.filter()
    flashcards = flashcards.order_by(
        models.F("next_review_date").asc(nulls_first=True), "-created"
    )
    paginator = Paginator(flashcards, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    template_name = (
        "flashcards/index.html#flashcards" if request.htmx else "flashcards/index.html"
    )
    return TemplateResponse(
        request,
        template_name,
        {
            "page_obj": page_obj,
            "total_count": flashcards.count(),
            "form": form,
        },
    )


def create(request: HttpRequest):
    form = FlashCardCreateForm(request.POST or None, request=request)
    if request.method == "POST" and form.is_valid():
        form.instance.owner = request.user
        form.save()
        next_url = (
            "flashcards:create"
            if form.cleaned_data["return_to_add_new"]
            else "flashcards:index"
        )
        return HttpResponseClientRedirect(reverse(next_url))
    template_name = (
        "flashcards/create.html#form" if request.htmx else "flashcards/create.html"
    )
    return TemplateResponse(request, template_name, {"form": form})


def edit(request: HttpRequest, pk: int):
    flashcard = get_object_or_404(FlashCard.objects.filter(owner=request.user), pk=pk)
    form = FlashCardEditForm(
        instance=flashcard, data=request.POST or None, request=request
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        return HttpResponseClientRedirect(reverse("flashcards:index"))
    template_name = (
        "flashcards/edit.html#form" if request.htmx else "flashcards/edit.html"
    )
    return TemplateResponse(
        request, template_name, {"flashcard": flashcard, "form": form}
    )


def show_question(request: HttpRequest, pk: int):
    flashcard = get_object_or_404(FlashCard.objects.filter(owner=request.user), pk=pk)
    return TemplateResponse(
        request, "flashcards/index.html#card_question", {"flashcard": flashcard}
    )


def show_answer(request: HttpRequest, pk: int):
    flashcard = get_object_or_404(FlashCard.objects.filter(owner=request.user), pk=pk)
    return TemplateResponse(
        request, "flashcards/index.html#card_answer", {"flashcard": flashcard}
    )


@require_http_methods(["POST"])
def delete(request: HttpRequest, pk: int):
    flashcard = get_object_or_404(FlashCard.objects.filter(owner=request.user), pk=pk)
    flashcard.delete()
    return HttpResponseClientRedirect(reverse("flashcards:index"))


def create_from_document(request: HttpRequest):
    form = FlashCardFromDocument(request.POST or None, request=request)
    if request.method == "POST" and form.is_valid():
        topic = form.cleaned_data["topic"]
        document: UploadedDocument = form.cleaned_data["document"]
        key_question = form.cleaned_data["key_question"]
        result = make_flashcards_from(
            source_text=document.get_relevant_text_for(key_question),
            key_question=key_question,
            card_type=form.cleaned_data["card_type"],
            topic_id=topic.id if topic else None,
        )
        save_llm_flashcards_to_session(request, result)
        return HttpResponseClientRedirect(reverse("flashcards:triage"))

    return TemplateResponse(
        request,
        "flashcards/create_from_document.html",
        {"form": FlashCardFromDocument(request=request)},
    )


def triage(request: HttpRequest):
    if flashcards := load_llm_flashcards_from_session(request):
        return TemplateResponse(
            request, "flashcards/triage.html", {"flashcards": flashcards}
        )
    raise Http404()


def edit_llm_flashcard(request: HttpRequest, id: str):
    flashcards = load_llm_flashcards_from_session(request)
    flashcard = [flashcard for flashcard in flashcards if flashcard.id == id][0]
    form = LLMFlashCard(
        request.POST or None,
        initial={
            "question": flashcard.question,
            "answer": flashcard.answer,
            "card_type": flashcard.card_type,
        },
    )
    if request.POST and form.is_valid():
        flashcard.question = form.cleaned_data["question"]
        flashcard.answer = form.cleaned_data["answer"]
        save_llm_flashcards_to_session(request, flashcards)
        return HttpResponseClientRedirect(reverse("flashcards:triage"))
    return TemplateResponse(
        request,
        "flashcards/triage.html#edit_flashcard",
        {
            "form": form,
            "url": reverse("flashcards:edit_llm_flashcard", kwargs={"id": id}),
        },
    )


@require_http_methods(["POST"])
def save_llm_flashcards(request: HttpRequest):
    flashcards = load_llm_flashcards_from_session(request)
    selected_flashcards = request.POST.getlist("selected_flashcards")
    db_flashcards = [
        FlashCard(
            question=flashcard.question,
            answer=flashcard.answer,
            owner=request.user,
            card_type=flashcard.card_type,
        )
        for flashcard in flashcards
        if flashcard.id in selected_flashcards
    ]
    if topic_id := flashcards[0].topic_id:
        topic = Topic.objects.get(id=topic_id)
        for f in db_flashcards:
            f.topic = topic

    FlashCard.objects.bulk_create(db_flashcards, ignore_conflicts=True)
    delete_llm_flashcards_from_session(request)
    return redirect("flashcards:index")

leerming/gifts/views.py
from django.db import models
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseClientRedirect
from django_htmx.http import retarget

from .forms import GiftForm
from .models import Gift
from leerming.flashcards.filters import FilterForm as FlashCardFilterForm
from leerming.users.models import User

GIFT_PARAMS_SESSION_KEY = "gift_params"


def set_recipient(request: HttpRequest):
    form = GiftForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if FlashCardFilterForm(request.POST, request=request).filter().count() == 0:
            form.add_error(None, "Vous ne pouvez pas envoyer un cadeau sans carte.")
            return retarget(HttpResponse(form.render()), "#dialog-form")
        request.session[GIFT_PARAMS_SESSION_KEY] = request.POST
        return redirect("gifts:confirm_send")

    return HttpResponse(form.render())


def confirm_send(request: HttpRequest):
    data = dict(request.session[GIFT_PARAMS_SESSION_KEY])
    recipient_email = data.pop("recipient_email")
    flashcards = FlashCardFilterForm(data, request=request).filter()
    if request.method == "POST":
        Gift.create(
            sender=request.user,
            recipient=User.objects.get(email=recipient_email),
            flashcards=flashcards,
        )
        return HttpResponseClientRedirect(reverse("gifts:index"))
    return TemplateResponse(
        request,
        "gifts/confirm_send.html",
        {
            "flashcard_count": flashcards.count(),
            "recipient_email": recipient_email,
            "topic_list": flashcards.exclude(topic__isnull=True)
            .values_list("topic__title", flat=True)
            .distinct(),
        },
    )


def index(request: HttpRequest):
    return TemplateResponse(
        request,
        "gifts/index.html",
        {
            "gifts": Gift.objects.filter(
                models.Q(sender=request.user) | models.Q(recipient=request.user)
            )
            .select_related("sender", "recipient")
            .annotate(
                sent_by_user=models.Case(
                    models.When(sender=request.user, then=models.Value(True)),
                    default=models.Value(False),
                    output_field=models.BooleanField(),
                )
            )
            .order_by("-created")
        },
    )


@require_http_methods(["POST"])
def open_gift(request: HttpRequest, pk: int):
    gift = get_object_or_404(Gift, pk=pk)
    gift.open()
    return HttpResponseClientRedirect(reverse("flashcards:index"))


@require_http_methods(["POST"])
def cancel_send(request: HttpRequest):
    request.session.pop(GIFT_PARAMS_SESSION_KEY, None)
    return HttpResponseClientRedirect(reverse("flashcards:index"))

leerming/templates/reviews/details.html
{% extends "base.html" %}

{% block content %}

    {{ review }}
    {{ review.creation_date }}
    {{ review.score_percentages }}
{% endblock content %}

leerming/templates/reviews/end.html
{% extends "base.html" %}

{% block body %}
    <div class="dark:bg-slate-900 bg-gray-100 flex h-full items-center py-16">
        <main class="w-full max-w-md md:max-w-2xl mx-auto p-6">
            <div
                class="flex flex-col bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
                <h3 class="text-2xl md:text-4xl font-bold text-gray-800 dark:text-white">
                    {% trans "Bon travail, la révision est terminée" %}
                </h3>
                <a href="{% url "reviews:index" %}" class="mt-3 inline-flex items-center gap-2 text-sm md:text-lg font-medium text-blue-500 hover:text-blue-700">
                    {% trans 'Révisions' %}
                    <svg class="w-2.5 h-auto" width="16" height="16" viewBox="0 0 16 16" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M5 1L10.6869 7.16086C10.8637 7.35239 10.8637 7.64761 10.6869 7.83914L5 14" stroke="currentColor"
                              stroke-width="2" stroke-linecap="round" />
                    </svg>
                </a>
            </div>
        </main>
    </div>
{% endblock body %}

leerming/templates/reviews/no_cards_to_review.html
{% extends "base.html" %}

{% block body %}
    <div class="dark:bg-slate-900 bg-gray-100 flex h-full items-center py-16">
        <main class="w-full max-w-md md:max-w-2xl mx-auto p-6">
            <div
                class="flex flex-col bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
                <h3 class="text-2xl md:text-4xl font-bold text-gray-800 dark:text-white">
                    {% trans "Aucune carte trouver" %}
                </h3>
                <p class="mt-2  text-gray-800 dark:text-gray-400">
                    {% if no_cards %}
                        {% trans "Vous n'avez encore aucune carte pour démarrer une révision" %}
                    {% else %}
                        {% blocktrans %}
                            Aucune de vos cartes actuelle ne peut etre utiliser pour la revision d'aujourd'hui,
                            soit vous les avez toutes maitriser, soit leurs niveau ne correspond pas a la révision d'aujourd'hui.
                        {% endblocktrans %}
                    {% endif %}
                </p>
                <a href="{% url "flashcards:create" %}"
                   class="mt-3 inline-flex items-center gap-2 text-sm md:text-lg font-medium text-blue-500 hover:text-blue-700">
                    {% trans 'Nouvelle carte' %}
                    <svg class="w-2.5 h-auto" width="16" height="16" viewBox="0 0 16 16" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M5 1L10.6869 7.16086C10.8637 7.35239 10.8637 7.64761 10.6869 7.83914L5 14"
                              stroke="currentColor" stroke-width="2" stroke-linecap="round" />
                    </svg>
                </a>
            </div>
        </main>
    </div>
{% endblock body %}

leerming/templates/reviews/show_current_card.html
{% extends "base.html" %}


{% partialdef answer_revealed %}
    <div
        class="flex flex-col bg-white border shadow-sm rounded-xl dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">

        <div class="bg-gray-100 border-b rounded-t-xl py-3 px-4 md:py-4 md:px-5 dark:bg-gray-800 dark:border-gray-700">
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-500">
                {{ flashcard }}
            </p>
        </div>
        <div class="p-4 md:p-5 text-green-600 dark:text-green-200">
            <p class="text-2xl md:text-4xl">
                {{ flashcard.answer_display }}
            </p>
        </div>

        <div hx-target="body" hx-swap="innerHTML transition:true"
             class="flex w-full gap-2 bg-gray-100 border-t rounded-b-xl py-3 px-4 md:py-4 md:px-5 dark:bg-gray-800 dark:border-gray-700">
            <button type="button"
                    hx-post="{% url 'reviews:answer_card' %}" hx-vals='{"answer": false}'
                    class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-red-500 text-white hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
                {% trans 'Non' %}
            </button>
            <button
                class="grow py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border-2 border-gray-200 dark:border-gray-700 font-semibold text-gray-500 dark:text-gray-300  text-sm">
                {% trans 'Avez vous eu la bonne réponse ?' %}
            </button>

            <button type="button"
                    hx-post="{% url 'reviews:answer_card' %}" hx-vals='{"answer": true}'
                    class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-green-500 text-white hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
                {% trans 'Oui' %}
            </button>

        </div>
    </div>

{% endpartialdef answer_revealed %}

{% block body %}
    <div class="absolute top-0 right-0 text-xl md:text-4xl dark:text-gray-400 p-2 md:p-3 m-3 border rounded">
        {{ step }}
    </div>
    <div class="dark:bg-slate-900 bg-gray-100 flex h-full items-center py-16">
        <main class="w-full max-w-md md:max-w-2xl mx-auto p-6 sample-transition">
            <div id="answer-revealed"
                 class="flex flex-col bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7] dark:text-gray-400">
                <p hx-get="{% url "reviews:reveal_answer" %}"
                   hx-target="#answer-revealed"
                   hx-swap="outerHTML transition:true"
                   class="cursor-pointer text-2xl md:text-4xl">{{ card }}</p>
            </div>
        </main>
    </div>
{% endblock body %}

leerming/templates/reviews/start.html
{% extends "base.html" %}
{% load l10n %}

{% block body %}
    <div class="absolute top-0 right-0 text-xl md:text-4xl dark:text-gray-400 p-2 md:p-3 m-3">
        <a href="{% url "reviews:index" %}"
           class="py-[.688rem] px-4 inline-flex justify-center items-center gap-2 rounded-md border-2 border-gray-200 font-semibold text-blue-500 hover:text-white hover:bg-blue-500 hover:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:border-gray-700 dark:hover:border-blue-500">
            {% trans '<< Retour' %}
        </a>
    </div>
    <div class="dark:bg-slate-900 bg-gray-100 flex h-full items-center py-16">
        <main class="w-full max-w-md md:max-w-2xl mx-auto p-6">
            <div
                class="flex flex-col bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
                <h3 class="text-2xl md:text-4xl font-bold text-gray-800 dark:text-white">
                    {% trans "Révision du" %} - {{ review_date|date:"d/m/Y" }}
                </h3>

                <p class="mt-2 text-gray-800 dark:text-gray-400">
                    {% blocktrans %}
                        Par défault toutes les carte prévu pour la séance du jour seront prises en compte, mais vous pouvez limiter les carts aux sujets
                        qui vous interessent en cochant les sujets ci-dessous.
                    {% endblocktrans %}
                </p>

                <form id="review-start-form" hx-post=".">
                    {% partialdef form inline=True %}

                        {% include "forms/non_field_errors.html" with form=form %}
                        {% include "forms/hidden_fields.html" with form=form %}
                        <div class="grid sm:grid-cols-2 gap-2 my-4">
                            {% for choice in form.topics %}
                                <label for="{{ choice.id_for_label }}"
                                       class="flex p-3  w-full bg-white border border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400">
                                    <input
                                        type="checkbox"
                                        class="shrink-0 mt-0.5 border-gray-200 rounded text-blue-600 pointer-events-none focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-gray-800"
                                        name="{{ form.topics.name }}"
                                        id="{{ choice.id_for_label }}"
                                        {% for value, label in form.fields.topics.choices %}
                                            {% if label == choice.choice_label %} value="{{ value }}" {% endif %}
                                        {% endfor %}
                                        {% if choice.checked %}checked{% endif %}
                                    >
                                    <span class="text-sm text-gray-500 ml-3 dark:text-gray-400">{{ choice.choice_label }}</span>
                                </label>
                            {% endfor %}
                        </div>

                    {% endpartialdef %}
                </form>
                <button type="submit" form="review-start-form"
                        class="w-full py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border cursor-pointer border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
                    {% heroicon_outline "rocket-launch" width="16" height="16" %}
                    {% trans 'Démarrer' %}
                </button>
            </a>
        </div>
    </main>
    </div>
{% endblock body %}