config/urls.py
from functools import partial

from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import include
from django.urls import path
from django.urls import reverse
from django.views import defaults as default_views

from leerming.profiles.decorators import profile_required

decorator_include_login_and_profile = partial(
    decorator_include,
    (login_required, profile_required),
)

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("schema-viewer/", include("schema_viewer.urls")),
    path("account/", include("allauth.urls")),
    path(
        "profiles/",
        decorator_include(
            login_required, "leerming.profiles.urls", namespace="profiles"
        ),
    ),
    path(
        "flashcards/",
        decorator_include_login_and_profile(
            "leerming.flashcards.urls", namespace="flashcards"
        ),
    ),
    path(
        "reviews/",
        decorator_include_login_and_profile(
            "leerming.reviews.urls", namespace="reviews"
        ),
    ),
    path(
        "gifts/",
        decorator_include_login_and_profile("leerming.gifts.urls", namespace="gifts"),
    ),
    path(
        "documents/",
        decorator_include_login_and_profile(
            "leerming.documents.urls", namespace="documents"
        ),
    ),
    path(
        "",
        lambda request: HttpResponseRedirect(reverse("flashcards:index")),
        name="home",
    ),  # TODO: replace by a landing page at some point
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

leerming/documents/urls.py
from django.urls import path

from . import views

app_name = "documents"

urlpatterns = [
    path("", views.index, name="index"),
    path("upload/", views.upload, name="upload"),
    path("get-form/", views.get_form, name="get_form"),
    path("select/", views.select, name="select"),
    path("upload-status/<str:task_id>/", views.upload_status, name="upload_status"),
    path(
        "upload-progress/<str:task_id>/", views.upload_progress, name="upload_progress"
    ),
]

leerming/gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"

urlpatterns = [
    path("", views.index, name="index"),
    path("set-recipient/", views.set_recipient, name="set_recipient"),
    path("confirm-send/", views.confirm_send, name="confirm_send"),
    path("cancel-send/", views.cancel_send, name="cancel_send"),
    path("open/<int:pk>/", views.open_gift, name="open"),
]

leerming/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
]

leerming/reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"


urlpatterns = [
    path("", views.index, name="index"),
    path("no-cards-to-review/", views.no_cards_to_review, name="no_cards_to_review"),
    path("start/", views.start, name="start"),
    path("show-current-card/", views.show_current_card, name="show_current_card"),
    path("move-to-next-card/", views.move_to_next_card, name="move_to_next_card"),
    path("end/", views.end, name="end"),
    path("reveal-answer/", views.reveal_answer, name="reveal_answer"),
    path("answer-card/", views.answer_card, name="answer_card"),
    path("<review_id>/", views.details, name="details"),
]

leerming/documents/models.py
from __future__ import annotations

from pathlib import Path

import httpx
import stamina
from bs4 import BeautifulSoup
from django.conf import settings
from django.db import models
from django.db.models.query import QuerySet
from django.utils.translation import gettext_lazy as _
from docx import Document as DocxDocument
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import FakeEmbeddings
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import Document as LangchainTextDoc
from langchain.text_splitter import RecursiveCharacterTextSplitter
from llama_hub.youtube_transcript import YoutubeTranscriptReader
from model_utils.models import TimeStampedModel
from pgvector.django import L2Distance
from pgvector.django import VectorField

from leerming.users.models import User

EMBEDDING_SIZE = 1536

TEXT_CHUNK_SIZE = 1000
TEXT_CHUNK_OVERLAP = 100

if settings.DEBUG:
    openai_embeddings = FakeEmbeddings(size=EMBEDDING_SIZE)
else:
    openai_embeddings = OpenAIEmbeddings()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=TEXT_CHUNK_SIZE, chunk_overlap=TEXT_CHUNK_OVERLAP
)


@stamina.retry(on=httpx.HTTPError, attempts=3)
def get_title_from(*, url: str):
    response = httpx.get(url, follow_redirects=True)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    # Find the first available title (h1, h2, h3)
    first_title = (
        soup.find("title")
        or soup.find("h1")
        or soup.find("h2")
        or soup.find("h3")
        or soup.find("h4")
    )
    return first_title.text.strip()


class UploadedDocument(TimeStampedModel):
    chunks: QuerySet[DocumentChunk]

    class DocType(models.TextChoices):
        PDF_DOC = "PDF_DOC", _("Document PDF")
        DOCX_DOC = "DOCX_DOC", _("Document Word")
        WEB_DOC = "HTML_DOC", _("Page web")
        YOUTUBE_VIDEO = "YOUTUBE_VIDEO", _("Vidéo Youtube")
        RAW_TEXT = "RAW_TEXT", _("Texte brut")

    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="uploaded_documents"
    )
    title = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    doc_type = models.CharField(max_length=255, choices=DocType.choices)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "title"], name="unique_uploaded_document"
            )
        ]

    def __str__(self):
        return self.title

    def get_relevant_chunks_for(self, query: str) -> QuerySet[DocumentChunk]:
        embedded_query = openai_embeddings.embed_query(query)
        return self.chunks.order_by(L2Distance("embedding", embedded_query))[:2]  # noqa

    def get_relevant_text_for(self, query: str):
        chunks = self.get_relevant_chunks_for(query)
        return "\n".join(chunk.content for chunk in chunks)

    def create_chunks(self, documents: list[LangchainTextDoc]) -> None:
        texts = text_splitter.split_documents(documents)
        vectors = openai_embeddings.embed_documents([t.page_content for t in texts])

        chunks = [
            DocumentChunk(
                document=self,
                content=texts[index].page_content,
                embedding=vector,
            )
            for index, vector in enumerate(vectors)
        ]
        DocumentChunk.objects.bulk_create(chunks)

    @classmethod
    def create_from_pdf_file(
        cls, *, temp_file: Path, title: str, owner: User
    ) -> UploadedDocument:
        loader = PyPDFLoader(str(temp_file))
        documents = loader.load_and_split()
        temp_file.unlink(missing_ok=True)
        uploaded_document = cls.objects.create(
            title=title, url="", doc_type=cls.DocType.PDF_DOC, owner=owner
        )
        uploaded_document.create_chunks(documents=documents)
        return uploaded_document

    @classmethod
    def create_from_docx_file(
        cls, *, temp_file: Path, title: str, owner: User
    ) -> UploadedDocument:
        docx = DocxDocument(str(temp_file))
        documents = [LangchainTextDoc(page_content=p.text) for p in docx.paragraphs]
        temp_file.unlink(missing_ok=True)
        uploaded_document = cls.objects.create(
            title=title, url="", doc_type=cls.DocType.DOCX_DOC, owner=owner
        )
        uploaded_document.create_chunks(documents=documents)
        return uploaded_document

    @classmethod
    def create_from_web_page(cls, *, url: str, owner: User, title) -> UploadedDocument:
        loader = UnstructuredURLLoader(
            urls=[url], continue_on_failure=False, headers={"User-Agent": "value"}
        )
        documents = loader.load()
        uploaded_document = cls.objects.create(
            title=title, url=url, doc_type=cls.DocType.WEB_DOC, owner=owner
        )
        uploaded_document.create_chunks(documents=documents)
        return uploaded_document

    @classmethod
    def create_from_raw_text(
        cls, *, text: str, owner: User, title: str
    ) -> UploadedDocument:
        uploaded_document = cls.objects.create(
            title=title, url="", doc_type=cls.DocType.RAW_TEXT, owner=owner
        )
        uploaded_document.create_chunks(documents=[LangchainTextDoc(page_content=text)])
        return uploaded_document

    @classmethod
    def create_from_youtube(cls, *, url: str, owner: User, title) -> UploadedDocument:
        loader = YoutubeTranscriptReader()
        documents = loader.load_data(ytlinks=[url])
        documents = [d.to_langchain_format() for d in documents]
        uploaded_document = cls.objects.create(
            title=title, url=url, doc_type=cls.DocType.YOUTUBE_VIDEO, owner=owner
        )
        uploaded_document.create_chunks(documents=documents)
        return uploaded_document

    @classmethod
    def get_create_func(cls, doc_type: DocType) -> callable:
        return {
            cls.DocType.YOUTUBE_VIDEO: cls.create_from_youtube,
            cls.DocType.PDF_DOC: cls.create_from_pdf_file,
            cls.DocType.DOCX_DOC: cls.create_from_docx_file,
            cls.DocType.WEB_DOC: cls.create_from_web_page,
            cls.DocType.RAW_TEXT: cls.create_from_raw_text,
        }.get(doc_type)


class DocumentChunk(TimeStampedModel):
    document = models.ForeignKey(
        UploadedDocument, on_delete=models.CASCADE, related_name="chunks"
    )
    content = models.TextField()
    embedding = VectorField(dimensions=EMBEDDING_SIZE)

leerming/core/views.py
from django.shortcuts import render
from django.http import HttpRequest


def index(request: HttpRequest):
    return render(request, "core/index.html")

leerming/documents/views.py
from django.db import IntegrityError
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django_htmx.http import reswap
from django_htmx.http import retarget
from django_htmx.http import trigger_client_event
from django_q.tasks import async_task
from django_q.tasks import result

from .forms import UploadForm
from .models import UploadedDocument
from leerming.users.models import User


def _create_document(doc_type: str, owner_id: int, params: dict) -> int | None:
    owner = User.objects.get(id=owner_id)
    create_func = UploadedDocument.get_create_func(doc_type)
    try:
        doc = create_func(owner=owner, **params)
        return doc.id
    except IntegrityError:
        return


def select(request: HttpRequest):
    documents = request.user.uploaded_documents.all().order_by("-created")
    response = TemplateResponse(
        request,
        "documents/select.html",
        {
            "documents": documents,
            "selected": int(request.GET.get("selected", default=documents.first().id)),
        },
    )
    if new_target := request.GET.get("retarget"):
        response = retarget(response, f"#{new_target}")
    return trigger_client_event(response, "showSubmitBtn", {})


def upload(request: HttpRequest):
    data = (request.POST, request.FILES) if request.method == "POST" else (None, None)
    form = UploadForm(*data, context={"user": request.user})
    if form.is_valid():
        cleaned_data = form.cleaned_data
        task_id = async_task(
            _create_document,
            doc_type=cleaned_data.pop("doc_type"),
            owner_id=request.user.id,
            params=cleaned_data,
        )
        return redirect(reverse("documents:upload_progress", args=[task_id]))
    response = TemplateResponse(
        request,
        "documents/upload.html",
        {
            "form": form,
            "user_has_existing_documents": request.user.uploaded_documents.exists(),
        },
    )
    if not form.is_valid() and request.method == "POST":
        response = retarget(response, "#upload-card")
        return reswap(response, "outerHTML")
    return trigger_client_event(response, "hideSubmitBtn", {})


def upload_progress(request: HttpRequest, task_id: str):
    return TemplateResponse(
        request, "documents/upload_progress.html", {"task_id": task_id}
    )


#  try for 6 min max for now, query for the result every 3 seconds with a max of 120 attempts
MAX_NBR_OF_TRY = 120
MILLISECONDS_WAIT = 3000


def upload_status(request: HttpRequest, task_id: str):
    nbr_of_try = request.session.get("nbr_of_try", 1)
    select_url = reverse("documents:select") + "?retarget=upload-card"
    if nbr_of_try > MAX_NBR_OF_TRY:
        # maybe add a message to tell the user to retry or check if task failed
        del request.session["nbr_of_try"]
        return redirect(select_url)
    request.session["nbr_of_try"] = nbr_of_try + 1
    if document_id := result(task_id, MILLISECONDS_WAIT):
        del request.session["nbr_of_try"]
        return redirect(f"{select_url}&selected={document_id}")
    return redirect(reverse("documents:upload_progress", args=[task_id]))


def get_form(request: HttpRequest):
    return HttpResponse(UploadForm(initial=request.GET).render())


def index(request: HttpRequest):
    if request.user.uploaded_documents.exists():
        return redirect("documents:select")
    return redirect("documents:upload")

leerming/gifts/views.py
from django.db import models
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseClientRedirect
from django_htmx.http import retarget

from .forms import GiftForm
from .models import Gift
from leerming.flashcards.filters import FilterForm as FlashCardFilterForm
from leerming.users.models import User

GIFT_PARAMS_SESSION_KEY = "gift_params"


def set_recipient(request: HttpRequest):
    form = GiftForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if FlashCardFilterForm(request.POST, request=request).filter().count() == 0:
            form.add_error(None, "Vous ne pouvez pas envoyer un cadeau sans carte.")
            return retarget(HttpResponse(form.render()), "#dialog-form")
        request.session[GIFT_PARAMS_SESSION_KEY] = request.POST
        return redirect("gifts:confirm_send")

    return HttpResponse(form.render())


def confirm_send(request: HttpRequest):
    data = dict(request.session[GIFT_PARAMS_SESSION_KEY])
    recipient_email = data.pop("recipient_email")
    flashcards = FlashCardFilterForm(data, request=request).filter()
    if request.method == "POST":
        Gift.create(
            sender=request.user,
            recipient=User.objects.get(email=recipient_email),
            flashcards=flashcards,
        )
        return HttpResponseClientRedirect(reverse("gifts:index"))
    return TemplateResponse(
        request,
        "gifts/confirm_send.html",
        {
            "flashcard_count": flashcards.count(),
            "recipient_email": recipient_email,
            "topic_list": flashcards.exclude(topic__isnull=True)
            .values_list("topic__title", flat=True)
            .distinct(),
        },
    )


def index(request: HttpRequest):
    return TemplateResponse(
        request,
        "gifts/index.html",
        {
            "gifts": Gift.objects.filter(
                models.Q(sender=request.user) | models.Q(recipient=request.user)
            )
            .select_related("sender", "recipient")
            .annotate(
                sent_by_user=models.Case(
                    models.When(sender=request.user, then=models.Value(True)),
                    default=models.Value(False),
                    output_field=models.BooleanField(),
                )
            )
            .order_by("-created")
        },
    )


@require_http_methods(["POST"])
def open_gift(request: HttpRequest, pk: int):
    gift = get_object_or_404(Gift, pk=pk)
    gift.open()
    return HttpResponseClientRedirect(reverse("flashcards:index"))


@require_http_methods(["POST"])
def cancel_send(request: HttpRequest):
    request.session.pop(GIFT_PARAMS_SESSION_KEY, None)
    return HttpResponseClientRedirect(reverse("flashcards:index"))

leerming/templates/documents/select.html
<div
    id="select-document-card"
    class="my-4 bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">


    <fieldset class="mb-5 grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6">
        <legend class="sr-only">Documents</legend>


        {% for doc in documents %}
            <div class="">
                <input
                    type="radio"
                    name="document"
                    value="{{ doc.id }}"
                    id="option_{{ doc.id }}"
                    class="peer hidden [&:checked_+_label_svg]:block"
                    {% if selected == doc.id %} checked {% endif %}

                />

                <label
                    for="option_{{ doc.id }}"
                    class="block cursor-pointer rounded-lg border bg-white p-4 text-sm font-medium shadow-sm hover:border-gray-200 peer-checked:border-blue-500 peer-checked:ring-1 peer-checked:ring-blue-500 dark:bg-slate-900 dark:border-gray-800"
                >
                    <span class="flex items-center justify-between">
                        <span class="text-gray-800 dark:text-gray-200">{{ doc.title }}</span>

                        <svg
                            class="hidden h-5 w-5 text-blue-600"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </span>

                    <span class="mt-2 text-gray-500">{{ doc.get_doc_type_display }}</span>
                </label>
            </div>
        {% endfor %}

    </fieldset>


    <a hx-get="{% url "documents:upload" %}"
       hx-target="#select-document-card"
       hx-swap="outerHTML transition:true"
       class="cursor-pointer text-white bg-blue-700 hover:bg-blue-800 focus:ring-4
              focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600
              dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
        {% trans "Ajouter un document" %}
    </a>
</div>

leerming/templates/documents/upload.html
<div id="upload-card"
     class="my-4 relative bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
    {% block form %}
        <form
            hx-target="#upload-progress"
            hx-post="{% url "documents:upload" %}"
            id="upload-form"
            hx-encoding='multipart/form-data'>
            {{ form }}
        </form>

    {% endblock form %}
    <input hx-indicator=".htmx-indicator.upload" id="upload-button" form="upload-form" type="submit"
           value="{% trans "Soumettre" %}"
           class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">

    {% if user_has_existing_documents %}
        <a hx-get="{% url "documents:select" %}" hx-target="#upload-card" hx-swap="outerHTML transition:true"
           class="cursor-pointer px-5 py-2.5 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-gray-500 text-white hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-offset-gray-800">
            {% trans "Sélectionner existant" %}
        </a>

    {% endif %}
    <div id="upload-progress"></div>

    <div class="htmx-indicator upload absolute top-0 left-0 w-full h-full bg-white/[.5] rounded-md dark:bg-gray-800/[.4]"></div>

    <div class="htmx-indicator upload absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
        <div class="animate-spin inline-block w-6 h-6 border-[3px] border-current border-t-transparent text-blue-600 rounded-full"
             role="status" aria-label="loading">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

</div>

leerming/templates/documents/upload_progress.html
<div hx-get="{% url "documents:upload_status" task_id %}"
     hx-indicator=".htmx-indicator.upload"
     hx-target="this"
     hx-swap="outerHTML transition:true"
     hx-trigger="load"></div>