config/urls.py
from functools import partial

from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import include
from django.urls import path
from django.urls import reverse
from django.views import defaults as default_views

from leerming.profiles.decorators import profile_required

decorator_include_login_and_profile = partial(
    decorator_include,
    (login_required, profile_required),
)

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("schema-viewer/", include("schema_viewer.urls")),
    path("account/", include("allauth.urls")),
    path(
        "profiles/",
        decorator_include(
            login_required, "leerming.profiles.urls", namespace="profiles"
        ),
    ),
    path(
        "flashcards/",
        decorator_include_login_and_profile(
            "leerming.flashcards.urls", namespace="flashcards"
        ),
    ),
    path(
        "reviews/",
        decorator_include_login_and_profile(
            "leerming.reviews.urls", namespace="reviews"
        ),
    ),
    path(
        "gifts/",
        decorator_include_login_and_profile("leerming.gifts.urls", namespace="gifts"),
    ),
    path(
        "documents/",
        decorator_include_login_and_profile(
            "leerming.documents.urls", namespace="documents"
        ),
    ),
    path(
        "",
        lambda request: HttpResponseRedirect(reverse("flashcards:index")),
        name="home",
    ),  # TODO: replace by a landing page at some point
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

leerming/gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"

urlpatterns = [
    path("", views.index, name="index"),
    path("set-recipient/", views.set_recipient, name="set_recipient"),
    path("confirm-send/", views.confirm_send, name="confirm_send"),
    path("cancel-send/", views.cancel_send, name="cancel_send"),
    path("open/<int:pk>/", views.open_gift, name="open"),
]

leerming/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
]

leerming/reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"


urlpatterns = [
    path("", views.index, name="index"),
    path("no-cards-to-review/", views.no_cards_to_review, name="no_cards_to_review"),
    path("start/", views.start, name="start"),
    path("show-current-card/", views.show_current_card, name="show_current_card"),
    path("move-to-next-card/", views.move_to_next_card, name="move_to_next_card"),
    path("end/", views.end, name="end"),
    path("reveal-answer/", views.reveal_answer, name="reveal_answer"),
    path("answer-card/", views.answer_card, name="answer_card"),
    path("<review_id>/", views.details, name="details"),
]

leerming/profiles/models.py
import datetime as dt
import zoneinfo

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_lifecycle import AFTER_CREATE
from django_lifecycle import AFTER_UPDATE
from django_lifecycle import BEFORE_SAVE
from django_lifecycle import hook
from django_lifecycle import LifecycleModelMixin
from model_utils.models import TimeStampedModel

from leerming.reviews.models import Review
from leerming.reviews.models import ScheduleManager


TIMEZONES_CHOICES = [(tz, tz) for tz in zoneinfo.available_timezones()]


class Profile(LifecycleModelMixin, TimeStampedModel):
    class Weekday(models.IntegerChoices):
        MONDAY = 0, _("Lundi")
        TUESDAY = 1, _("Mardi")
        WEDNESDAY = 2, _("Mercredi")
        THURSDAY = 3, _("Jeudi")
        FRIDAY = 4, _("Vendredi")
        SATURDAY = 5, _("Samedi")
        SUNDAY = 6, _("Dimanche")

    user = models.OneToOneField(
        "users.User", related_name="profile", on_delete=models.CASCADE
    )
    full_name = models.CharField(_("full name"), max_length=200, blank=True)
    short_name = models.CharField(_("short name"), max_length=50, blank=True)
    review_days = ArrayField(
        models.PositiveSmallIntegerField(choices=Weekday.choices),
        verbose_name=_("Jours de révision"),
    )
    review_time = models.TimeField(
        verbose_name=_("Heure de révision"), default="18:00"
    )
    timezone = models.CharField(
        verbose_name=_("Fuseau horaire"),
        max_length=50,
        default="UTC",
        choices=TIMEZONES_CHOICES,
    )
    email_notifications_enabled = models.BooleanField(
        default=True, verbose_name=_("Notifications par email")
    )

    def __str__(self):
        return self.full_name or self.short_name or f"Profile of {self.user}"

    @cached_property
    def review_scheduler_name(self) -> str:
        return f"{self.user.email}_review_scheduler"

    def is_in_review_days(self, day: Weekday) -> bool:
        return day in self.review_days

    def get_next_review_datetime(
        self, from_date: dt.date | None = None, include_from_date: bool = False
    ) -> dt.datetime:
        # prevent the function to return dates in the past
        today = timezone.now().date()
        from_date = max(from_date, today)

        if include_from_date:
            condition_check = (  # noqa E731
                lambda weekday: weekday >= from_date.weekday()
            )
        else:
            condition_check = lambda weekday: weekday > from_date.weekday()  # noqa E731

        next_weekday = next(
            (weekday for weekday in self.review_days if condition_check(weekday)),
            self.review_days[0],
        )

        if include_from_date:
            next_review_date = from_date
        else:
            next_review_date = from_date + dt.timedelta(days=1)

        # loop until we find a day that matches the next_weekday
        while next_review_date.weekday() != next_weekday:
            next_review_date += dt.timedelta(days=1)

        next_run = dt.datetime.combine(next_review_date, self.review_time)
        return timezone.make_aware(next_run, zoneinfo.ZoneInfo(self.timezone))

    @hook(BEFORE_SAVE)
    def sort_review_days(self):
        self.review_days = sorted(self.review_days)

    @hook(
        AFTER_UPDATE,
        when_any=["review_days", "review_time", "timezone"],
        has_changed=True,
    )
    def update_scheduler(self):
        ScheduleManager.remove(reviewer=self.user)
        self.register_for_next_review()

    @hook(AFTER_CREATE)
    def register_for_next_review(self):
        now = timezone.now()
        today = now.date()
        last_review_date = Review.get_last_review_date(reviewer=self.user)
        from_date = last_review_date or today
        next_review_datetime = self.get_next_review_datetime(
            from_date=from_date,
            include_from_date=last_review_date and last_review_date != today,
        )
        ScheduleManager.add(reviewer=self.user, review_datetime=next_review_datetime)

leerming/core/forms.py
from django import forms
from django.forms.renderers import TemplatesSetting


class FormRenderer(TemplatesSetting):
    form_template_name = "forms/form.html"


def clean_masked_phone(form: forms.Form):
    # a mask is applied on phone in the frontend, so we need to clean before saving to the db
    phone = form.cleaned_data.get("phone", None)
    if phone:
        phone = phone.replace("-", "").replace(" ", "")
    return phone

leerming/profiles/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Profile


class ProfileForm(forms.ModelForm):
    review_days = forms.MultipleChoiceField(
        choices=Profile.Weekday.choices,
        initial=[
            Profile.Weekday.MONDAY,
            Profile.Weekday.TUESDAY,
            Profile.Weekday.WEDNESDAY,
            Profile.Weekday.THURSDAY,
            Profile.Weekday.FRIDAY,
            Profile.Weekday.SATURDAY,
            Profile.Weekday.SUNDAY,
        ],
        label=_("Jours de révision"),
        widget=forms.SelectMultiple(attrs={"class": "tom-select"}),
    )

    class Meta:
        model = Profile
        fields = ["review_days", "review_time", "timezone"]
        widgets = {
            "timezone": forms.Select(attrs={"class": "tom-select"}),
            "review_time": forms.TimeInput(format="%H:%M", attrs={"type": "time"}),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        review_days = cleaned_data.get("review_days")
        review_days = [int(day) for day in review_days]
        cleaned_data["review_days"] = review_days
        return cleaned_data


class ProfileEditForm(ProfileForm):
    class Meta(ProfileForm.Meta):
        fields = ProfileForm.Meta.fields + [
            "short_name",
            "full_name",
            "email_notifications_enabled",
        ]

leerming/core/views.py
from django.shortcuts import render
from django.http import HttpRequest


def index(request: HttpRequest):
    return render(request, "core/index.html")

leerming/documents/views.py
from django.db import IntegrityError
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django_htmx.http import reswap
from django_htmx.http import retarget
from django_htmx.http import trigger_client_event
from django_q.tasks import async_task
from django_q.tasks import result

from .forms import UploadForm
from .models import UploadedDocument
from leerming.users.models import User


def _create_document(doc_type: str, owner_id: int, params: dict) -> int | None:
    owner = User.objects.get(id=owner_id)
    create_func = UploadedDocument.get_create_func(doc_type)
    try:
        doc = create_func(owner=owner, **params)
        return doc.id
    except IntegrityError:
        return


def select(request: HttpRequest):
    documents = request.user.uploaded_documents.all().order_by("-created")
    response = TemplateResponse(
        request,
        "documents/select.html",
        {
            "documents": documents,
            "selected": int(request.GET.get("selected", default=documents.first().id)),
        },
    )
    if new_target := request.GET.get("retarget"):
        response = retarget(response, f"#{new_target}")
    return trigger_client_event(response, "showSubmitBtn", {})


def upload(request: HttpRequest):
    data = (request.POST, request.FILES) if request.method == "POST" else (None, None)
    form = UploadForm(*data, context={"user": request.user})
    if form.is_valid():
        cleaned_data = form.cleaned_data
        task_id = async_task(
            _create_document,
            doc_type=cleaned_data.pop("doc_type"),
            owner_id=request.user.id,
            params=cleaned_data,
        )
        return redirect(reverse("documents:upload_progress", args=[task_id]))
    response = TemplateResponse(
        request,
        "documents/upload.html",
        {
            "form": form,
            "user_has_existing_documents": request.user.uploaded_documents.exists(),
        },
    )
    if not form.is_valid() and request.method == "POST":
        response = retarget(response, "#upload-card")
        return reswap(response, "outerHTML")
    return trigger_client_event(response, "hideSubmitBtn", {})


def upload_progress(request: HttpRequest, task_id: str):
    return TemplateResponse(
        request, "documents/upload_progress.html", {"task_id": task_id}
    )


#  try for 6 min max for now, query for the result every 3 seconds with a max of 120 attempts
MAX_NBR_OF_TRY = 120
MILLISECONDS_WAIT = 3000


def upload_status(request: HttpRequest, task_id: str):
    nbr_of_try = request.session.get("nbr_of_try", 1)
    select_url = reverse("documents:select") + "?retarget=upload-card"
    if nbr_of_try > MAX_NBR_OF_TRY:
        # maybe add a message to tell the user to retry or check if task failed
        del request.session["nbr_of_try"]
        return redirect(select_url)
    request.session["nbr_of_try"] = nbr_of_try + 1
    if document_id := result(task_id, MILLISECONDS_WAIT):
        del request.session["nbr_of_try"]
        return redirect(f"{select_url}&selected={document_id}")
    return redirect(reverse("documents:upload_progress", args=[task_id]))


def get_form(request: HttpRequest):
    return HttpResponse(UploadForm(initial=request.GET).render())


def index(request: HttpRequest):
    if request.user.uploaded_documents.exists():
        return redirect("documents:select")
    return redirect("documents:upload")

leerming/gifts/views.py
from django.db import models
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseClientRedirect
from django_htmx.http import retarget

from .forms import GiftForm
from .models import Gift
from leerming.flashcards.filters import FilterForm as FlashCardFilterForm
from leerming.users.models import User

GIFT_PARAMS_SESSION_KEY = "gift_params"


def set_recipient(request: HttpRequest):
    form = GiftForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if FlashCardFilterForm(request.POST, request=request).filter().count() == 0:
            form.add_error(None, "Vous ne pouvez pas envoyer un cadeau sans carte.")
            return retarget(HttpResponse(form.render()), "#dialog-form")
        request.session[GIFT_PARAMS_SESSION_KEY] = request.POST
        return redirect("gifts:confirm_send")

    return HttpResponse(form.render())


def confirm_send(request: HttpRequest):
    data = dict(request.session[GIFT_PARAMS_SESSION_KEY])
    recipient_email = data.pop("recipient_email")
    flashcards = FlashCardFilterForm(data, request=request).filter()
    if request.method == "POST":
        Gift.create(
            sender=request.user,
            recipient=User.objects.get(email=recipient_email),
            flashcards=flashcards,
        )
        return HttpResponseClientRedirect(reverse("gifts:index"))
    return TemplateResponse(
        request,
        "gifts/confirm_send.html",
        {
            "flashcard_count": flashcards.count(),
            "recipient_email": recipient_email,
            "topic_list": flashcards.exclude(topic__isnull=True)
            .values_list("topic__title", flat=True)
            .distinct(),
        },
    )


def index(request: HttpRequest):
    return TemplateResponse(
        request,
        "gifts/index.html",
        {
            "gifts": Gift.objects.filter(
                models.Q(sender=request.user) | models.Q(recipient=request.user)
            )
            .select_related("sender", "recipient")
            .annotate(
                sent_by_user=models.Case(
                    models.When(sender=request.user, then=models.Value(True)),
                    default=models.Value(False),
                    output_field=models.BooleanField(),
                )
            )
            .order_by("-created")
        },
    )


@require_http_methods(["POST"])
def open_gift(request: HttpRequest, pk: int):
    gift = get_object_or_404(Gift, pk=pk)
    gift.open()
    return HttpResponseClientRedirect(reverse("flashcards:index"))


@require_http_methods(["POST"])
def cancel_send(request: HttpRequest):
    request.session.pop(GIFT_PARAMS_SESSION_KEY, None)
    return HttpResponseClientRedirect(reverse("flashcards:index"))

leerming/profiles/views.py
from django.http import HttpRequest
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from .decorators import profile_required
from .forms import ProfileEditForm
from .forms import ProfileForm
from .models import Profile


def register(request: HttpRequest):
    form = ProfileForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        Profile.objects.get_or_create(user=request.user, defaults=form.cleaned_data)
        return redirect("flashcards:index")
    return TemplateResponse(request, "profiles/register.html", {"form": form})


@profile_required
def edit(request: HttpRequest):
    profile = request.user.profile
    form = ProfileEditForm(request.POST or None, instance=profile)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("profiles:edit")
    return TemplateResponse(request, "profiles/edit.html", {"form": form})

leerming/templates/profiles/edit.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'vendors/tom-select/tom-select.complete.min.js' %}"></script>
{% endblock extra_head %}
{% block content %}
    <div
        class="bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
        <h1 class="mb-2 text-xl font-bold text-gray-800 dark:text-white">
            {% trans "Modifier votre profile" %}
        </h1>
        {% block form %}
            <form method="post" id="edit-form">
                {% csrf_token %}
                {{ form }}
            </form>
            <!-- <div class="my-4 hs-tooltip flex items-center">
                <input type="checkbox" id="hs-tooltip-example" class="sp_notify_prompt hs-tooltip-toggle relative shrink-0 w-[3.25rem] h-7 bg-gray-100 checked:bg-none checked:bg-blue-600 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 border border-transparent ring-1 ring-transparent focus:border-blue-600 focus:ring-blue-600 ring-offset-white focus:outline-none appearance-none dark:bg-gray-700 dark:checked:bg-blue-600 dark:focus:ring-offset-gray-800

                                                                      before:inline-block before:w-6 before:h-6 before:bg-white checked:before:bg-blue-200 before:translate-x-0 checked:before:translate-x-full before:shadow before:rounded-full before:transform before:ring-0 before:transition before:ease-in-out before:duration-200 dark:before:bg-gray-400 dark:checked:before:bg-blue-200">
                <label for="hs-tooltip-example" class="text-sm text-gray-500 ml-3 dark:text-gray-400">Allow push
                    notifications</label>
                <div class="hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible opacity-0 transition-opacity inline-block absolute invisible z-10 py-1 px-2 bg-gray-900 text-xs font-medium text-white rounded-md shadow-sm dark:bg-slate-700"
                     role="tooltip">
                    Enable push notifications
                </div>
            </div> -->
        {% endblock form %}
        <button form="edit-form" type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
            {% trans "Enrégister" %}
        </button>

    </div>


{% endblock content %}

{% block javascript %}
    <script>
        new TomSelect("#id_review_days", {
            plugins: {
                remove_button: {
                    title: 'Remove this item',
                }
            },
            persist: false,
            createOnBlur: true,
            create: true
        });
        new TomSelect("#id_timezone");
    </script>
{% endblock javascript %}

leerming/templates/profiles/register.html
{% extends "account/base.html" %}
{% load i18n static %}

{% block extra_head %}
    <script src="{% static 'vendors/tom-select/tom-select.complete.min.js' %}"></script>
{% endblock extra_head %}

{% block content %}
    <div class="mt-7 bg-white border border-gray-200 rounded-xl shadow-sm dark:bg-gray-800 dark:border-gray-700">
        <div class="p-4 sm:p-7">
            <div class="text-center">
                <h1
                    class="block text-2xl font-bold text-gray-800 dark:text-white">{% translate "Plannifié vos seances d'apprentissage" %}</h1>
                <p
                    class="mt-2 mb-4 text-sm text-gray-600 dark:text-gray-400">{% blocktrans %}Choissizer les jours et l'heure a
                        laquelle vous souhaitez effectuer vos seances de revisons, vous receverz une notification a l'heure definit.
                        Vous pouvez modifier plus tard changer ces valeurs sur votre profil.{% endblocktrans %}</p>
            </div>

            <form method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="{% translate "Soumettre" %}"
                       class="py-3 px-4  w-full rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
            </form>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script>
        new TomSelect("#id_review_days", {
            plugins: {
                remove_button: {
                    title: 'Remove this item',
                }
            },
            persist: false,
            createOnBlur: true,
            create: true
        });
        new TomSelect("#id_timezone");
    </script>
{% endblock javascript %}