config/urls.py
from functools import partial

from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import include
from django.urls import path
from django.urls import reverse
from django.views import defaults as default_views

from leerming.profiles.decorators import profile_required

decorator_include_login_and_profile = partial(
    decorator_include,
    (login_required, profile_required),
)

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("schema-viewer/", include("schema_viewer.urls")),
    path("account/", include("allauth.urls")),
    path(
        "profiles/",
        decorator_include(
            login_required, "leerming.profiles.urls", namespace="profiles"
        ),
    ),
    path(
        "flashcards/",
        decorator_include_login_and_profile(
            "leerming.flashcards.urls", namespace="flashcards"
        ),
    ),
    path(
        "reviews/",
        decorator_include_login_and_profile(
            "leerming.reviews.urls", namespace="reviews"
        ),
    ),
    path(
        "gifts/",
        decorator_include_login_and_profile("leerming.gifts.urls", namespace="gifts"),
    ),
    path(
        "documents/",
        decorator_include_login_and_profile(
            "leerming.documents.urls", namespace="documents"
        ),
    ),
    path(
        "",
        lambda request: HttpResponseRedirect(reverse("flashcards:index")),
        name="home",
    ),  # TODO: replace by a landing page at some point
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

leerming/flashcards/urls.py
from django.urls import path

from . import views

app_name = "flashcards"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path(
        "create-from-document/", views.create_from_document, name="create_from_document"
    ),
    path("triage/", views.triage, name="triage"),
    path(
        "edit-llm-flashcard/<str:id>/",
        views.edit_llm_flashcard,
        name="edit_llm_flashcard",
    ),
    path("save-llm-flashcards/", views.save_llm_flashcards, name="save_llm_flashcards"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/show-answer/", views.show_answer, name="show_answer"),
    path("<int:pk>/show-question/", views.show_question, name="show_question"),
]

leerming/gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"

urlpatterns = [
    path("", views.index, name="index"),
    path("set-recipient/", views.set_recipient, name="set_recipient"),
    path("confirm-send/", views.confirm_send, name="confirm_send"),
    path("cancel-send/", views.cancel_send, name="cancel_send"),
    path("open/<int:pk>/", views.open_gift, name="open"),
]

leerming/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
]

leerming/reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"


urlpatterns = [
    path("", views.index, name="index"),
    path("no-cards-to-review/", views.no_cards_to_review, name="no_cards_to_review"),
    path("start/", views.start, name="start"),
    path("show-current-card/", views.show_current_card, name="show_current_card"),
    path("move-to-next-card/", views.move_to_next_card, name="move_to_next_card"),
    path("end/", views.end, name="end"),
    path("reveal-answer/", views.reveal_answer, name="reveal_answer"),
    path("answer-card/", views.answer_card, name="answer_card"),
    path("<review_id>/", views.details, name="details"),
]

leerming/flashcards/models.py
import datetime as dt

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class Topic(TimeStampedModel):
    created_by = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="topics"
    )
    title = models.CharField(
        verbose_name=_("Titre"),
        max_length=255,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["created_by", "title"],
                name="unique_topic",
            )
        ]

    def __str__(self) -> str:
        return self.title


class FlashCard(TimeStampedModel):
    LEVEL_TO_DAYS_MAP = {
        1: 1,
        2: 2,
        3: 4,
        4: 7,
        5: 15,
        6: 30,
        7: 60,
    }

    DIFFICULTY_TO_LEVEL_MAP = {
        "EASY": (5, 6, 7),
        "MEDIUM": (3, 4),
        "HARD": (1, 2),
    }

    class Difficulty(models.TextChoices):
        EASY = "EASY", _("Facile")
        MEDIUM = "MEDIUM", _("Moyen")
        HARD = "HARD", _("Difficile")

    class CardType(models.TextChoices):
        FRONT_BACK = "FRONT_BACK", _("Recto / Verso")
        FILL_IN_THE_GAP = "FILL_IN_THE_GAP", _("Remplissage")

    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="flashcards"
    )
    topic = models.ForeignKey(
        Topic,
        verbose_name=_("Sujet"),
        on_delete=models.CASCADE,
        related_name="flashcards",
        blank=True,
        null=True,
    )
    card_type = models.CharField(
        verbose_name=_("Type de carte"),
        choices=CardType.choices,
        max_length=20,
        default=CardType.FILL_IN_THE_GAP,
    )
    level = models.IntegerField(
        verbose_name=_("Niveau"),
        default=1,
        help_text=_(
            "Indique la difficulté de la carte, de 1 à 7 (le niveau le plus difficile)."
        ),
        validators=[MinValueValidator(1), MaxValueValidator(7)],
    )
    # this is a user friendly version of the level
    difficulty = models.CharField(
        verbose_name=_("Difficulté"),
        choices=Difficulty.choices,
        max_length=6,
        default=Difficulty.HARD,
    )
    mastered_at = models.DateTimeField(
        verbose_name=_("Maîtrisée à"), blank=True, null=True
    )
    question = models.CharField(
        verbose_name=_("Question / Texte à remplir"), max_length=250
    )
    answer = models.CharField(verbose_name=_("Réponse"), max_length=200)
    next_review_date = models.DateField(
        verbose_name=_("Date de la prochaine révision"), blank=True, null=True
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "question", "answer"], name="unique_flashcard"
            )
        ]

    def __str__(self):
        if self.card_type == self.CardType.FRONT_BACK:
            return self.question
        return self.question.replace(self.answer, "[...]")

    @property
    def answer_display(self) -> str:
        if self.card_type == self.CardType.FRONT_BACK:
            return self.answer
        return self.question

    def update_level_from_difficulty(self) -> None:
        # when user manually change the difficulty
        self.level = self.DIFFICULTY_TO_LEVEL_MAP.get(self.difficulty)[0]
        review_interval = dt.timedelta(days=self.LEVEL_TO_DAYS_MAP[self.level])
        # would be even better if the from_date was the user last_review date
        self.next_review_date = self.owner.profile.get_next_review_datetime(
            from_date=timezone.now().date() + review_interval, include_from_date=True
        )
        self.save()

    def review(self, correct_answer: bool, for_date: dt.date) -> None:
        if self.mastered_at:
            return
        if correct_answer and self.level < 7:
            self.level += 1
        elif correct_answer and self.level == 7:
            self.mastered_at = for_date
            self.next_review_date = None
            self.save()
            return
        else:
            self.level = 1
        review_interval = dt.timedelta(days=self.LEVEL_TO_DAYS_MAP[self.level])
        self.difficulty = FlashCard.get_difficulty_for(self.level)
        self.next_review_date = self.owner.profile.get_next_review_datetime(
            from_date=for_date + review_interval, include_from_date=True
        )
        self.save()

    @staticmethod
    def get_difficulty_for(level) -> str:
        for key, value in FlashCard.DIFFICULTY_TO_LEVEL_MAP.items():
            if level in value:
                return key

leerming/core/forms.py
from django import forms
from django.forms.renderers import TemplatesSetting


class FormRenderer(TemplatesSetting):
    form_template_name = "forms/form.html"


def clean_masked_phone(form: forms.Form):
    # a mask is applied on phone in the frontend, so we need to clean before saving to the db
    phone = form.cleaned_data.get("phone", None)
    if phone:
        phone = phone.replace("-", "").replace(" ", "")
    return phone

leerming/core/views.py
from django.shortcuts import render
from django.http import HttpRequest


def index(request: HttpRequest):
    return render(request, "core/index.html")

leerming/documents/views.py
from django.db import IntegrityError
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django_htmx.http import reswap
from django_htmx.http import retarget
from django_htmx.http import trigger_client_event
from django_q.tasks import async_task
from django_q.tasks import result

from .forms import UploadForm
from .models import UploadedDocument
from leerming.users.models import User


def _create_document(doc_type: str, owner_id: int, params: dict) -> int | None:
    owner = User.objects.get(id=owner_id)
    create_func = UploadedDocument.get_create_func(doc_type)
    try:
        doc = create_func(owner=owner, **params)
        return doc.id
    except IntegrityError:
        return


def select(request: HttpRequest):
    documents = request.user.uploaded_documents.all().order_by("-created")
    response = TemplateResponse(
        request,
        "documents/select.html",
        {
            "documents": documents,
            "selected": int(request.GET.get("selected", default=documents.first().id)),
        },
    )
    if new_target := request.GET.get("retarget"):
        response = retarget(response, f"#{new_target}")
    return trigger_client_event(response, "showSubmitBtn", {})


def upload(request: HttpRequest):
    data = (request.POST, request.FILES) if request.method == "POST" else (None, None)
    form = UploadForm(*data, context={"user": request.user})
    if form.is_valid():
        cleaned_data = form.cleaned_data
        task_id = async_task(
            _create_document,
            doc_type=cleaned_data.pop("doc_type"),
            owner_id=request.user.id,
            params=cleaned_data,
        )
        return redirect(reverse("documents:upload_progress", args=[task_id]))
    response = TemplateResponse(
        request,
        "documents/upload.html",
        {
            "form": form,
            "user_has_existing_documents": request.user.uploaded_documents.exists(),
        },
    )
    if not form.is_valid() and request.method == "POST":
        response = retarget(response, "#upload-card")
        return reswap(response, "outerHTML")
    return trigger_client_event(response, "hideSubmitBtn", {})


def upload_progress(request: HttpRequest, task_id: str):
    return TemplateResponse(
        request, "documents/upload_progress.html", {"task_id": task_id}
    )


#  try for 6 min max for now, query for the result every 3 seconds with a max of 120 attempts
MAX_NBR_OF_TRY = 120
MILLISECONDS_WAIT = 3000


def upload_status(request: HttpRequest, task_id: str):
    nbr_of_try = request.session.get("nbr_of_try", 1)
    select_url = reverse("documents:select") + "?retarget=upload-card"
    if nbr_of_try > MAX_NBR_OF_TRY:
        # maybe add a message to tell the user to retry or check if task failed
        del request.session["nbr_of_try"]
        return redirect(select_url)
    request.session["nbr_of_try"] = nbr_of_try + 1
    if document_id := result(task_id, MILLISECONDS_WAIT):
        del request.session["nbr_of_try"]
        return redirect(f"{select_url}&selected={document_id}")
    return redirect(reverse("documents:upload_progress", args=[task_id]))


def get_form(request: HttpRequest):
    return HttpResponse(UploadForm(initial=request.GET).render())


def index(request: HttpRequest):
    if request.user.uploaded_documents.exists():
        return redirect("documents:select")
    return redirect("documents:upload")

leerming/gifts/views.py
from django.db import models
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import HttpResponseClientRedirect
from django_htmx.http import retarget

from .forms import GiftForm
from .models import Gift
from leerming.flashcards.filters import FilterForm as FlashCardFilterForm
from leerming.users.models import User

GIFT_PARAMS_SESSION_KEY = "gift_params"


def set_recipient(request: HttpRequest):
    form = GiftForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if FlashCardFilterForm(request.POST, request=request).filter().count() == 0:
            form.add_error(None, "Vous ne pouvez pas envoyer un cadeau sans carte.")
            return retarget(HttpResponse(form.render()), "#dialog-form")
        request.session[GIFT_PARAMS_SESSION_KEY] = request.POST
        return redirect("gifts:confirm_send")

    return HttpResponse(form.render())


def confirm_send(request: HttpRequest):
    data = dict(request.session[GIFT_PARAMS_SESSION_KEY])
    recipient_email = data.pop("recipient_email")
    flashcards = FlashCardFilterForm(data, request=request).filter()
    if request.method == "POST":
        Gift.create(
            sender=request.user,
            recipient=User.objects.get(email=recipient_email),
            flashcards=flashcards,
        )
        return HttpResponseClientRedirect(reverse("gifts:index"))
    return TemplateResponse(
        request,
        "gifts/confirm_send.html",
        {
            "flashcard_count": flashcards.count(),
            "recipient_email": recipient_email,
            "topic_list": flashcards.exclude(topic__isnull=True)
            .values_list("topic__title", flat=True)
            .distinct(),
        },
    )


def index(request: HttpRequest):
    return TemplateResponse(
        request,
        "gifts/index.html",
        {
            "gifts": Gift.objects.filter(
                models.Q(sender=request.user) | models.Q(recipient=request.user)
            )
            .select_related("sender", "recipient")
            .annotate(
                sent_by_user=models.Case(
                    models.When(sender=request.user, then=models.Value(True)),
                    default=models.Value(False),
                    output_field=models.BooleanField(),
                )
            )
            .order_by("-created")
        },
    )


@require_http_methods(["POST"])
def open_gift(request: HttpRequest, pk: int):
    gift = get_object_or_404(Gift, pk=pk)
    gift.open()
    return HttpResponseClientRedirect(reverse("flashcards:index"))


@require_http_methods(["POST"])
def cancel_send(request: HttpRequest):
    request.session.pop(GIFT_PARAMS_SESSION_KEY, None)
    return HttpResponseClientRedirect(reverse("flashcards:index"))

leerming/profiles/views.py
from django.http import HttpRequest
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from .decorators import profile_required
from .forms import ProfileEditForm
from .forms import ProfileForm
from .models import Profile


def register(request: HttpRequest):
    form = ProfileForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        Profile.objects.get_or_create(user=request.user, defaults=form.cleaned_data)
        return redirect("flashcards:index")
    return TemplateResponse(request, "profiles/register.html", {"form": form})


@profile_required
def edit(request: HttpRequest):
    profile = request.user.profile
    form = ProfileEditForm(request.POST or None, instance=profile)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("profiles:edit")
    return TemplateResponse(request, "profiles/edit.html", {"form": form})

leerming/templates/flashcards/edit.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'vendors/tom-select/tom-select.complete.min.js' %}"></script>
{% endblock extra_head %}

{% block content %}

    <div
        class="bg-white border shadow-sm rounded-xl p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
        <h1 class="mb-2 text-xl font-bold text-gray-800 dark:text-white">
            {% trans "Modifier une Carte" %}
        </h1>
        {% partialdef form inline=True %}
            <form hx-post="."
                  hx-target="this"
                  hx-swap="outerHTML"
                  method="post" id="edit-form">
                {{ form }}
            </form>
        {% endpartialdef form %}
        <button form="edit-form" type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
            {% trans "Enrégister" %}
        </button>

        <button
            class="text-white bg-red-700 focus:ring-4 focus:ring-red-300 font-medium text-sm px-5 py-2.5 mb-2 rounded-lg focus:outline-none"
            hx-confirm="{% trans "Êtes vous sure de vouloir supprimer cette carte ?" %}"
            hx-post="{% url "flashcards:delete" flashcard.pk %}">{% trans "Supprimer cette carte" %}</button>
    </div>


{% endblock content %}

{% block javascript %}
    <script>
        new TomSelect("#id_topic", {
            create: true,
            sortField: {
                field: "text",
                direction: "asc"
            }
        });
    </script>
{% endblock javascript %}

leerming/templates/flashcards/index.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block breadcrumb %}
    {% trans "Cartes" as menu %}
    {% include "partials/breadcrumb.html" with menu=menu %}
{% endblock breadcrumb %}

{% partialdef card_answer %}
    <div id="flashcard-{{ flashcard.id }}"
         hx-get="{% url 'flashcards:show_question' flashcard.pk %}" hx-target="this" hx-swap="outerHTML transition:true"
         class="flex flex-col justify-center border cursor-pointer shadow-sm rounded-md p-4 md:p-5 text-white bg-teal-700 dark:border-teal-900">
        <p>{{ flashcard.answer_display }}</p>
    </div>
{% endpartialdef card_answer %}


{% block modal %}
    <dialog data-modal class="bg-white shadow-lg rounded-xl dark:bg-gray-800">
        <div class="p-4 sm:py-6 sm:p-10 text-center">
            <h3 class="mb-2 text-2xl font-bold text-gray-800 dark:text-gray-200">
                {% trans "Email du destinataire" %}
            </h3>
            <form hx-target="dialog"
                  hx-include="[id='filter-form']"
                  id="dialog-form"
                  hx-post="{% url 'gifts:set_recipient' %}"></form>
        </div>
        <div class="flex items-center">
            <button data-modal-close type="button"
                    class="p-4 w-full inline-flex justify-center items-center gap-2 rounded-bl-xl bg-gray-100 border border-transparent font-semibold text-gray-800 hover:text-blue-600 focus:outline-none focus:ring-2 ring-offset-white focus:ring-gray-100 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-600 dark:text-white dark:focus:ring-offset-gray-800"
                    data-hs-overlay="#hs-cookies">
                {% trans "Annuler" %}
            </button>
            <button type="submit" form="dialog-form"
                    class="p-4 w-full inline-flex justify-center items-center gap-2 rounded-br-xl border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800"
                    data-hs-overlay="#hs-cookies">
                {% trans "Soumettre" %}
            </button>
        </div>
    </dialog>
{% endblock modal %}
{% block javascript %}
    <script src="{% static 'javascript/modal.js' %}"></script>
{% endblock javascript %}
{% block content %}
    <header class="mb-6">
        <h1 class="block text-2xl font-bold text-gray-800 sm:text-3xl dark:text-white">{% trans "Vos Cartes" %}
            - {{ total_count }}</h1>
        <p class="mt-2 text-lg text-gray-800 dark:text-gray-400">{% blocktrans %} Toutes vos cartes de révisions, vous
            pouvez cliquer sur une carte pour voir la réponses associé.
            Toute les nouvelles carte commence avec le niveau difficile pour qu'elle soit evaluer des la prochaine
            revision,
            mais vous avez la possibilite de la mettre au niveau de votre choix (ce qui n'est pas
            recommander){% endblocktrans %}</p>
        <div class="mt-5 flex flex-col items-center gap-2 sm:flex-row sm:gap-3">
            <a href="{% url 'flashcards:create' %}"
               class="w-full sm:w-auto inline-flex justify-center items-center gap-x-3 text-center bg-blue-600 hover:bg-blue-700 border border-transparent text-white text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800">
                {% heroicon_outline "plus" width="16" height="16" %}
                {% translate "Nouvelle carte(s)" %}
            </a>
        </div>
    </header>

    <form hx-get="."
          hx-indicator=".htmx-indicator"
          hx-target="#flashcards"
          hx-trigger="keyup delay:500ms, change, search"
          hx-swap="innerHTML transition:true"
          class="my-5 flex flex-col xl:flex-row gap-2"
          id="filter-form"
    >
        {{ form }}
        <button hx-get="{% url 'gifts:set_recipient' %}"
                hx-target="#dialog-form"
                hx-include="[id='filter-form']"
                data-open-modal
                class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-gray-500 text-white hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-offset-gray-800">
            Envoyer a un ami
            {% heroicon_solid "paper-airplane" class="w-4 h-4" %}
        </button>
    </form>

    <div id="flashcards">
        {% partialdef flashcards inline=True %}

            <div class="relative grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-4 sm:gap-6">
                {% for flashcard in page_obj %}
                    {% partialdef card_question inline=True %}
                        <div id="flashcard-{{ flashcard.id }}"
                             class="flex flex-col justify-between max-w-2xl px-8 py-4 bg-white border shadow-sm  rounded-md p-4 md:p-5 dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
                            <div class="flex items-center justify-between">
                                <span class="text-sm font-light text-gray-600 dark:text-gray-400">
                                    {{ flashcard.topic|default:"" }}
                                </span>

                                <span
                                    {% if flashcard.difficulty == 'HARD' %}
                                        class="px-3 py-1 text-sm font-bold bg-red-500 text-white rounded"
                                    {% elif flashcard.difficulty == 'MEDIUM' %}
                                        class="px-3 py-1 text-sm font-bold bg-yellow-500 text-white rounded"
                                    {% else %}
                                        class="px-3 py-1 text-sm font-bold bg-green-500 text-white rounded"
                                    {% endif %}
                                    tabindex="0" role="button">{{ flashcard.get_difficulty_display }}</span>
                            </div>

                            <div class="mt-2">
                                <p hx-get="{% url 'flashcards:show_answer' flashcard.pk %}"
                                   hx-target="#flashcard-{{ flashcard.pk }}" hx-swap="outerHTML transition:true"
                                   class="mt-2 text-gray-800 dark:text-gray-400 cursor-pointer">{{ flashcard }}</p>

                            </div>

                            <div class="flex items-center justify-between mt-4">

                                {% if flashcard.next_review_date %}
                                    <p class="text-md text-gray-500 dark:text-gray-500">
                                        {{ flashcard.next_review_date|naturalday }}
                                    </p>
                                {% else %}
                                    <p class="text-md text-gray-500 dark:text-gray-500">
                                        {% trans "Prochaine révision" %}
                                    </p>
                                {% endif %}

                                <a href="{% url 'flashcards:edit' flashcard.pk %}"
                                   class="py-[.688rem] px-4 inline-flex justify-center items-center gap-2 rounded-md border-2 border-gray-200 font-semibold text-blue-500 hover:text-white hover:bg-blue-500 hover:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:border-gray-700 dark:hover:border-blue-500">
                                    {% trans "Édité" %}
                                    {% heroicon_outline "pencil" width="15" height="15" %}
                                </a>
                            </div>
                        </div>
                    {% endpartialdef card_question %}
                {% endfor %}


                <div class="htmx-indicator absolute top-0 left-0 w-full h-full bg-white/[.5] rounded-md dark:bg-gray-800/[.4]"></div>

                <div class="htmx-indicator absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                    <div class="animate-spin inline-block w-6 h-6 border-[3px] border-current border-t-transparent text-blue-600 rounded-full"
                         role="status" aria-label="loading">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>

            </div>

            <div
                class="mt-5 px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center">
                <div class="">
                    <p class="text-sm text-gray-600 dark:text-gray-400">
                        <span class="font-semibold text-gray-800 dark:text-gray-200">{{ page_obj|length }}</span> {% trans "résultats sur" %}
                        <span
                            class="font-semibold text-gray-800 dark:text-gray-200">{{ page_obj.paginator.count }}</span>
                    </p>
                </div>

                <div>
                    <div class="inline-flex gap-x-2">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'flashcards:index' %}?page={{ page_obj.previous_page_number }}"
                               class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800">
                                <svg class="w-3 h-3" width="16" height="16" viewBox="0 0 16 15" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M10.506 1.64001L4.85953 7.28646C4.66427 7.48172 4.66427 7.79831 4.85953 7.99357L10.506 13.64"
                                        stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                </svg>
                                Prev
                            </a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a href="{% url 'flashcards:index' %}?page={{ page_obj.next_page_number }}"
                               class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800">
                                Next
                                <svg class="w-3 h-3" width="16" height="16" viewBox="0 0 16 16" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path d="M4.50598 2L10.1524 7.64645C10.3477 7.84171 10.3477 8.15829 10.1524 8.35355L4.50598 14"
                                          stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                </svg>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endpartialdef flashcards %}

    </div>

{% endblock content %}